

const countries = [
{
  jp:"アイスランド",
  en:"iceland",
  code:"is",
  continent:"europe",
  capital:" レイキャビク / Reykjavik",
  population:" 約38万人 / ~0.38M",
  populationRank:180,
  landarea:" ~103K km²",
  areaRank:108,
  currency:" アイスランド・クローナ / ISK",
  language:" アイスランド語 / Icelandic",
  aliases:[]
},
{
  jp:"アイルランド",
  en:"ireland",
  code:"ie",
  continent:"europe",
  capital:" ダブリン / Dublin",
  population:" 約510万人 / ~5.1M",
  populationRank:122,
  landarea:" ~70K km²",
  areaRank:118,
  currency:" ユーロ / EUR",
  language:" 英語 / Irish",
  aliases:[]
},
{
  jp:"アゼルバイジャン",
  en:"azerbaijan",
  code:"az",
  continent:"asia",
  capital:" バクー / Baku",
  population:" 約1000万人 / ~10M",
  populationRank:91,
  landarea:" ~86.6K km²",
  areaRank:112,
  currency:" マナト / AZN",
  language:" アゼルバイジャン語 / Azerbaijani",
  aliases:[]
},
{
  jp:"アフガニスタン",
  en:"afghanistan",
  code:"af",
  continent:"asia",
  capital:" カブール / Kabul",
  population:" 約4100万人 / ~41M",
  populationRank:37,
  landarea:" ~652K km²",
  areaRank:41,
  currency:" アフガニ / AFN",
  language:" ダリー語 / Pashto",
  aliases:[]
},
{
  jp:"アメリカ",
  en:"united states",
  code:"us",
  continent:"northamerica",
  capital:" ワシントンD.C. / Washington, D.C.",
  population:" 約3.3億人 / ~330M",
  populationRank:3,
  landarea:" ~9,834K km²",
  areaRank:3,
  currency:" 米ドル / USD",
  language:" 英語 / English",
  aliases:["USA","アメリカ合衆国"]
},
{
  jp:"アラブ首長国連邦",
  en:"united arab emirates",
  code:"ae",
  continent:"asia",
  capital:" アブダビ / Abu Dhabi",
  population:" 約1000万人 / ~10M",
  populationRank:92,
  landarea:" ~83.6K km²",
  areaRank:114,
  currency:" UAEディルハム / AED",
  language:" アラビア語 / Arabic",
  aliases:["あらぶしゅちょうこくれんぽう","アラブシュチョウコクレンポウ"]
},
{
  jp:"アルジェリア",
  en:"algeria",
  code:"dz",
  continent:"africa",
  capital:" アルジェ / Algiers",
  population:" 約4500万人 / ~45M",
  populationRank:33,
  landarea:" ~2,381K km²",
  areaRank:10,
  currency:" ディナール / DZD",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"アルゼンチン",
  en:"argentina",
  code:"ar",
  continent:"southamerica",
  capital:" ブエノスアイレス / Buenos Aires",
  population:" 約4600万人 / ~46M",
  populationRank:32,
  landarea:" ~2,780K km²",
  areaRank:8,
  currency:" ペソ / ARS",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"アルバニア",
  en:"albania",
  code:"al",
  continent:"europe",
  capital:" ティラナ / Tirana",
  population:" 約280万人 / ~2.8M",
  populationRank:136,
  landarea:" ~28.7K km²",
  areaRank:140,
  currency:" レク / ALL",
  language:" アルバニア語 / Albanian",
  aliases:[]
},
{
  jp:"アルメニア",
  en:"armenia",
  code:"am",
  continent:"asia",
  capital:" エレバン / Yerevan",
  population:" 約280万人 / ~2.8M",
  populationRank:137,
  landarea:" ~29.7K km²",
  areaRank:138,
  currency:" ドラム / AMD",
  language:" アルメニア語 / Armenian",
  aliases:[]
},
{
  jp:"アンゴラ",
  en:"angola",
  code:"ao",
  continent:"africa",
  capital:" ルアンダ / Luanda",
  population:" 約3500万人 / ~35M",
  populationRank:45,
  landarea:" ~1,247K km²",
  areaRank:22,
  currency:" クワンザ / AOA",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"アンティグアバーブーダ",
  en:"antigua and barbuda",
  code:"ag",
  continent:"northamerica",
  capital:" セントジョンズ / St. John's",
  population:" 約10万人 / ~0.1M",
  populationRank:190,
  landarea:" ~0.44K km²",
  areaRank:182,
  currency:" 東カリブドル / XCD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"アンドラ",
  en:"andorra",
  code:"ad",
  continent:"europe",
  capital:" アンドラ・ラ・ベリャ / Andorra la Vella",
  population:" 約8万人 / ~0.08M",
  populationRank:193,
  landarea:" ~0.47K km²",
  areaRank:180,
  currency:" ユーロ / EUR",
  language:" カタルーニャ語 / Catalan",
  aliases:[]
},
{
  jp:"イエメン",
  en:"yemen",
  code:"ye",
  continent:"asia",
  capital:" サナア / Sana'a",
  population:" 約3400万人 / ~34M",
  populationRank:46,
  landarea:" ~528K km²",
  areaRank:49,
  currency:" イエメン・リアル / YER",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"イギリス",
  en:"united kingdom",
  code:"gb",
  continent:"europe",
  capital:" ロンドン / London",
  population:" 約6700万人 / ~67M",
  populationRank:22,
  landarea:" ~243K km²",
  areaRank:78,
  currency:" ポンド / GBP",
  language:" 英語 / English",
  aliases:["UK","英国"]
},
{
  jp:"イスラエル",
  en:"israel",
  code:"il",
  continent:"asia",
  capital:" エルサレム / Jerusalem",
  population:" 約970万人 / ~9.7M",
  populationRank:95,
  landarea:" ~22K km²",
  areaRank:150,
  currency:" 新シェケル / ILS",
  language:" ヘブライ語 / Hebrew",
  aliases:[]
},
{
  jp:"イタリア",
  en:"italy",
  code:"it",
  continent:"europe",
  capital:" ローマ / Rome",
  population:" 約5900万人 / ~59M",
  populationRank:25,
  landarea:" ~301K km²",
  areaRank:71,
  currency:" ユーロ / EUR",
  language:" イタリア語 / Italian",
  aliases:[]
},
{
  jp:"イラン",
  en:"iran",
  code:"ir",
  continent:"asia",
  capital:" テヘラン / Tehran",
  population:" 約8900万人 / ~89M",
  populationRank:17,
  landarea:" ~1,648K km²",
  areaRank:17,
  currency:" リアル / IRR",
  language:" ペルシャ語 / Persian",
  aliases:[]
},
{
  jp:"インド",
  en:"india",
  code:"in",
  continent:"asia",
  capital:" ニューデリー / New Delhi",
  population:" 約14.3億人 / ~1430M",
  populationRank:1,
  landarea:" ~3,287K km²",
  areaRank:7,
  currency:" ルピー / INR",
  language:" ヒンディー語 / Hindi",
  aliases:[]
},
{
  jp:"インドネシア",
  en:"indonesia",
  code:"id",
  continent:"asia",
  capital:" ジャカルタ / Jakarta",
  population:" 約2.8億人 / ~280M",
  populationRank:4,
  landarea:" ~1,905K km²",
  areaRank:14,
  currency:" ルピア / IDR",
  language:" インドネシア語 / Indonesian",
  aliases:[]
},
{
  jp:"ウガンダ",
  en:"uganda",
  code:"ug",
  continent:"africa",
  capital:" カンパラ / Kampala",
  population:" 約4800万人 / ~48M",
  populationRank:31,
  landarea:" ~241K km²",
  areaRank:79,
  currency:" ウガンダ・シリング / UGX",
  language:" 英語 / Swahili",
  aliases:[]
},
{
  jp:"ウクライナ",
  en:"ukraine",
  code:"ua",
  continent:"europe",
  capital:" キーウ / Kyiv",
  population:" 約3600万人 / ~36M",
  populationRank:41,
  landarea:" ~603K km²",
  areaRank:44,
  currency:" フリヴニャ / UAH",
  language:" ウクライナ語 / Ukrainian",
  aliases:[]
},
{
  jp:"ウズベキスタン",
  en:"uzbekistan",
  code:"uz",
  continent:"asia",
  capital:" タシュケント / Tashkent",
  population:" 約3600万人 / ~36M",
  populationRank:42,
  landarea:" ~447K km²",
  areaRank:56,
  currency:" スム / UZS",
  language:" ウズベク語 / Uzbek",
  aliases:[]
},
{
  jp:"ウルグアイ",
  en:"uruguay",
  code:"uy",
  continent:"southamerica",
  capital:" モンテビデオ / Montevideo",
  population:" 約350万人 / ~3.5M",
  populationRank:135,
  landarea:" ~176K km²",
  areaRank:90,
  currency:" ペソ / UYU",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"エクアドル",
  en:"ecuador",
  code:"ec",
  continent:"southamerica",
  capital:" キト / Quito",
  population:" 約1800万人 / ~18M",
  populationRank:65,
  landarea:" ~256K km²",
  areaRank:75,
  currency:" 米ドル / USD",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"エジプト",
  en:"egypt",
  code:"eg",
  continent:"africa",
  capital:" カイロ / Cairo",
  population:" 約1.1億人 / ~110M",
  populationRank:14,
  landarea:" ~1,002K km²",
  areaRank:30,
  currency:" エジプト・ポンド / EGP",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"エストニア",
  en:"estonia",
  code:"ee",
  continent:"europe",
  capital:" タリン / Tallinn",
  population:" 約130万人 / ~1.3M",
  populationRank:155,
  landarea:" ~45K km²",
  areaRank:129,
  currency:" ユーロ / EUR",
  language:" エストニア語 / Estonian",
  aliases:[]
},
{
  jp:"エスワティニ",
  en:"eswatini",
  code:"sz",
  continent:"africa",
  capital:" ムババーネ / Mbabane",
  population:" 約120万人 / ~1.2M",
  populationRank:156,
  landarea:" ~17K km²",
  areaRank:158,
  currency:" リランゲニ / SZL",
  language:" 英語 / Swati",
  aliases:[]
},
{
  jp:"エチオピア",
  en:"ethiopia",
  code:"et",
  continent:"africa",
  capital:" アディスアベバ / Addis Ababa",
  population:" 約1.2億人 / ~120M",
  populationRank:12,
  landarea:" ~1,104K km²",
  areaRank:27,
  currency:" ブル / ETB",
  language:" アムハラ語 / Amharic",
  aliases:[]
},
{
  jp:"エリトリア",
  en:"eritrea",
  code:"er",
  continent:"africa",
  capital:" アスマラ / Asmara",
  population:" 約360万人 / ~3.6M",
  populationRank:134,
  landarea:" ~117K km²",
  areaRank:101,
  currency:" ナクファ / ERN",
  language:" ティグリニャ語 / Tigrinya",
  aliases:[]
},
{
  jp:"エルサルバドル",
  en:"el salvador",
  code:"sv",
  continent:"northamerica",
  capital:" サンサルバドル / San Salvador",
  population:" 約650万人 / ~6.5M",
  populationRank:112,
  landarea:" ~21K km²",
  areaRank:152,
  currency:" 米ドル / USD",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"オーストラリア",
  en:"australia",
  code:"au",
  continent:"oceania",
  capital:" キャンベラ / Canberra",
  population:" 約2600万人 / ~26M",
  populationRank:55,
  landarea:" ~7,692K km²",
  areaRank:6,
  currency:" 豪ドル / AUD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"オーストリア",
  en:"austria",
  code:"at",
  continent:"europe",
  capital:" ウィーン / Vienna",
  population:" 約900万人 / ~9M",
  populationRank:99,
  landarea:" ~84K km²",
  areaRank:113,
  currency:" ユーロ / EUR",
  language:" ドイツ語 / German",
  aliases:[]
},
{
  jp:"オマーン",
  en:"oman",
  code:"om",
  continent:"asia",
  capital:" マスカット / Muscat",
  population:" 約460万人 / ~4.6M",
  populationRank:125,
  landarea:" ~309K km²",
  areaRank:70,
  currency:" リアル / OMR",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"オランダ",
  en:"netherlands",
  code:"nl",
  continent:"europe",
  capital:" アムステルダム / Amsterdam",
  population:" 約1700万人 / ~17M",
  populationRank:70,
  landarea:" ~41K km²",
  areaRank:131,
  currency:" ユーロ / EUR",
  language:" オランダ語 / Dutch",
  aliases:[]
},
{
  jp:"ガーナ",
  en:"ghana",
  code:"gh",
  continent:"africa",
  capital:" アクラ / Accra",
  population:" 約3400万人 / ~34M",
  populationRank:47,
  landarea:" ~238K km²",
  areaRank:80,
  currency:" セディ / GHS",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"カーボベルデ",
  en:"cape verde",
  code:"cv",
  continent:"africa",
  capital:" プライア / Praia",
  population:" 約60万人 / ~0.6M",
  populationRank:175,
  landarea:" ~4K km²",
  areaRank:171,
  currency:" エスクード / CVE",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"ガイアナ",
  en:"guyana",
  code:"gy",
  continent:"southamerica",
  capital:" ジョージタウン / Georgetown",
  population:" 約80万人 / ~0.8M",
  populationRank:169,
  landarea:" ~215K km²",
  areaRank:84,
  currency:" ガイアナ・ドル / GYD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"カザフスタン",
  en:"kazakhstan",
  code:"kz",
  continent:"asia",
  capital:" アスタナ / Astana",
  population:" 約2000万人 / ~20M",
  populationRank:64,
  landarea:" ~2,725K km²",
  areaRank:9,
  currency:" テンゲ / KZT",
  language:" カザフ語 / Kazakh",
  aliases:[]
},
{
  jp:"カタール",
  en:"qatar",
  code:"qa",
  continent:"asia",
  capital:" ドーハ / Doha",
  population:" 約280万人 / ~2.8M",
  populationRank:137,
  landarea:" ~11.6K km²",
  areaRank:158,
  currency:" リヤル / QAR",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"カナダ",
  en:"canada",
  code:"ca",
  continent:"northamerica",
  capital:" オタワ / Ottawa",
  population:" 約4000万人 / ~40M",
  populationRank:38,
  landarea:" ~9,985K km²",
  areaRank:2,
  currency:" カナダドル / CAD",
  language:" 英語 / French",
  aliases:[]
},
{
  jp:"ガボン",
  en:"gabon",
  code:"ga",
  continent:"africa",
  capital:" リーブルヴィル / Libreville",
  population:" 約240万人 / ~2.4M",
  populationRank:141,
  landarea:" ~268K km²",
  areaRank:73,
  currency:" CFAフラン / XAF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"カメルーン",
  en:"cameroon",
  code:"cm",
  continent:"africa",
  capital:" ヤウンデ / Yaoundé",
  population:" 約2800万人 / ~28M",
  populationRank:51,
  landarea:" ~475K km²",
  areaRank:54,
  currency:" CFAフラン / XAF",
  language:" フランス語 / English",
  aliases:[]
},
{
  jp:"ガンビア",
  en:"gambia",
  code:"gm",
  continent:"africa",
  capital:" バンジュール / Banjul",
  population:" 約270万人 / ~2.7M",
  populationRank:142,
  landarea:" ~11K km²",
  areaRank:159,
  currency:" ダラシ / GMD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"カンボジア",
  en:"cambodia",
  code:"kh",
  continent:"asia",
  capital:" プノンペン / Phnom Penh",
  population:" 約1700万人 / ~17M",
  populationRank:71,
  landarea:" ~181K km²",
  areaRank:88,
  currency:" リエル / KHR",
  language:" クメール語 / Khmer",
  aliases:[]
},
{
  jp:"ギニア",
  en:"guinea",
  code:"gn",
  continent:"africa",
  capital:" コナクリ / Conakry",
  population:" 約1400万人 / ~14M",
  populationRank:75,
  landarea:" ~246K km²",
  areaRank:78,
  currency:" ギニア・フラン / GNF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"ギニアビサウ",
  en:"guinea-bissau",
  code:"gw",
  continent:"africa",
  capital:" ビサウ / Bissau",
  population:" 約210万人 / ~2.1M",
  populationRank:146,
  landarea:" ~36K km²",
  areaRank:135,
  currency:" CFAフラン / XOF",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"キプロス",
  en:"cyprus",
  code:"cy",
  continent:"asia",
  capital:" ニコシア / Nicosia",
  population:" 約120万人 / ~1.2M",
  populationRank:156,
  landarea:" ~9.2K km²",
  areaRank:162,
  currency:" ユーロ / EUR",
  language:" ギリシャ語 / Turkish",
  aliases:[]
},
{
  jp:"ギリシャ",
  en:"greece",
  code:"gr",
  continent:"europe",
  capital:" アテネ / Athens",
  population:" 約1040万人 / ~10.4M",
  populationRank:87,
  landarea:" ~132K km²",
  areaRank:96,
  currency:" ユーロ / EUR",
  language:" ギリシャ語 / Greek",
  aliases:[]
},
{
  jp:"キリバス",
  en:"kiribati",
  code:"ki",
  continent:"oceania",
  capital:" タラワ / Tarawa",
  population:" 約13万人 / ~0.13M",
  populationRank:189,
  landarea:" ~0.81K km²",
  areaRank:174,
  currency:" 豪ドル / AUD",
  language:" キリバス語 / English",
  aliases:[]
},
{
  jp:"キルギス",
  en:"kyrgyzstan",
  code:"kg",
  continent:"asia",
  capital:" ビシュケク / Bishkek",
  population:" 約700万人 / ~7M",
  populationRank:110,
  landarea:" ~199K km²",
  areaRank:85,
  currency:" ソム / KGS",
  language:" キルギス語 / Russian",
  aliases:[]
},
{
  jp:"グアテマラ",
  en:"guatemala",
  code:"gt",
  continent:"northamerica",
  capital:" グアテマラシティ / Guatemala City",
  population:" 約1800万人 / ~18M",
  populationRank:67,
  landarea:" ~109K km²",
  areaRank:107,
  currency:" ケツァル / GTQ",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"クウェート",
  en:"kuwait",
  code:"kw",
  continent:"asia",
  capital:" クウェート市 / Kuwait City",
  population:" 約430万人 / ~4.3M",
  populationRank:128,
  landarea:" ~17.8K km²",
  areaRank:157,
  currency:" ディナール / KWD",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"グレナダ",
  en:"grenada",
  code:"gd",
  continent:"northamerica",
  capital:" セントジョージズ / St. George's",
  population:" 約11万人 / ~0.11M",
  populationRank:191,
  landarea:" ~0.34K km²",
  areaRank:183,
  currency:" 東カリブドル / XCD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"クロアチア",
  en:"croatia",
  code:"hr",
  continent:"europe",
  capital:" ザグレブ / Zagreb",
  population:" 約390万人 / ~3.9M",
  populationRank:130,
  landarea:" ~56.6K km²",
  areaRank:126,
  currency:" ユーロ / EUR",
  language:" クロアチア語 / Croatian",
  aliases:[]
},
{
  jp:"ケニア",
  en:"kenya",
  code:"ke",
  continent:"africa",
  capital:" ナイロビ / Nairobi",
  population:" 約5500万人 / ~55M",
  populationRank:27,
  landarea:" ~580K km²",
  areaRank:47,
  currency:" ケニア・シリング / KES",
  language:" 英語 / Swahili",
  aliases:[]
},
{
  jp:"コスタリカ",
  en:"costa rica",
  code:"cr",
  continent:"northamerica",
  capital:" サンホセ / San José",
  population:" 約520万人 / ~5.2M",
  populationRank:121,
  landarea:" ~51K km²",
  areaRank:129,
  currency:" コロン / CRC",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"コモロ",
  en:"comoros",
  code:"km",
  continent:"africa",
  capital:" モロニ / Moroni",
  population:" 約90万人 / ~0.9M",
  populationRank:168,
  landarea:" ~1.9K km²",
  areaRank:170,
  currency:" コモロ・フラン / KMF",
  language:" アラビア語 / French",
  aliases:[]
},
{
  jp:"コロンビア",
  en:"colombia",
  code:"co",
  continent:"southamerica",
  capital:" ボゴタ / Bogotá",
  population:" 約5200万人 / ~52M",
  populationRank:29,
  landarea:" ~1,142K km²",
  areaRank:25,
  currency:" ペソ / COP",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"コンゴ共和国",
  en:"republic of the congo",
  code:"cg",
  continent:"africa",
  capital:" ブラザヴィル / Brazzaville",
  population:" 約600万人 / ~6M",
  populationRank:118,
  landarea:" ~342K km²",
  areaRank:65,
  currency:" CFAフラン / XAF",
  language:" フランス語 / French",
  aliases:["congo","こんごきょうわこく","コンゴキョウワコク"]
},
{
  jp:"コンゴ民主共和国",
  en:"democratic republic of the congo",
  code:"cd",
  continent:"africa",
  capital:" キンシャサ / Kinshasa",
  population:" 約1.1億人 / ~110M",
  populationRank:15,
  landarea:" ~2,345K km²",
  areaRank:11,
  currency:" コンゴ・フラン / CDF",
  language:" フランス語 / French",
  aliases:["congo","コンゴミンシュキョウワコク","こんごみんしゅきょうわこく"]
},
{
  jp:"サウジアラビア",
  en:"saudi arabia",
  code:"sa",
  continent:"asia",
  capital:" リヤド / Riyadh",
  population:" 約3600万人 / ~36M",
  populationRank:40,
  landarea:" ~2,150K km²",
  areaRank:12,
  currency:" リヤル / SAR",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"サモア",
  en:"samoa",
  code:"ws",
  continent:"oceania",
  capital:" アピア / Apia",
  population:" 約20万人 / ~0.2M",
  populationRank:187,
  landarea:" ~2.8K km²",
  areaRank:168,
  currency:" タラ / WST",
  language:" サモア語 / English",
  aliases:[]
},
{
  jp:"サントメプリンシペ",
  en:"sao tome and principe",
  code:"st",
  continent:"africa",
  capital:" サントメ / São Tomé",
  population:" 約22万人 / ~0.22M",
  populationRank:185,
  landarea:" ~1K km²",
  areaRank:172,
  currency:" ドブラ / STN",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"ザンビア",
  en:"zambia",
  code:"zm",
  continent:"africa",
  capital:" ルサカ / Lusaka",
  population:" 約2000万人 / ~20M",
  populationRank:63,
  landarea:" ~752K km²",
  areaRank:39,
  currency:" クワチャ / ZMW",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"サンマリノ",
  en:"san marino",
  code:"sm",
  continent:"europe",
  capital:" サンマリノ / San Marino",
  population:" 約3万人 / ~0.03M",
  populationRank:195,
  landarea:" ~0.06K km²",
  areaRank:187,
  currency:" ユーロ / EUR",
  language:" イタリア語 / Italian",
  aliases:[]
},
{
  jp:"シエラレオネ",
  en:"sierra leone",
  code:"sl",
  continent:"africa",
  capital:" フリータウン / Freetown",
  population:" 約890万人 / ~8.9M",
  populationRank:97,
  landarea:" ~71.7K km²",
  areaRank:117,
  currency:" レオン / SLE",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ジブチ",
  en:"djibouti",
  code:"dj",
  continent:"africa",
  capital:" ジブチ / Djibouti",
  population:" 約120万人 / ~1.2M",
  populationRank:157,
  landarea:" ~23.2K km²",
  areaRank:149,
  currency:" ジブチ・フラン / DJF",
  language:" フランス語 / Arabic",
  aliases:[]
},
{
  jp:"ジャマイカ",
  en:"jamaica",
  code:"jm",
  continent:"northamerica",
  capital:" キングストン / Kingston",
  population:" 約280万人 / ~2.8M",
  populationRank:138,
  landarea:" ~11K km²",
  areaRank:160,
  currency:" ジャマイカ・ドル / JMD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ジョージア",
  en:"georgia",
  code:"ge",
  continent:"asia",
  capital:" トビリシ / Tbilisi",
  population:" 約370万人 / ~3.7M",
  populationRank:133,
  landarea:" ~69.7K km²",
  areaRank:119,
  currency:" ラリ / GEL",
  language:" ジョージア語 / Georgian",
  aliases:[]
},
{
  jp:"シリア",
  en:"syria",
  code:"sy",
  continent:"asia",
  capital:" ダマスカス / Damascus",
  population:" 約2400万人 / ~24M",
  populationRank:57,
  landarea:" ~185K km²",
  areaRank:87,
  currency:" シリア・ポンド / SYP",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"シンガポール",
  en:"singapore",
  code:"sg",
  continent:"asia",
  capital:" シンガポール / Singapore",
  population:" 約600万人 / ~6.0M",
  populationRank:117,
  landarea:" ~0.73K km²",
  areaRank:175,
  currency:" シンガポール・ドル / SGD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ジンバブエ",
  en:"zimbabwe",
  code:"zw",
  continent:"africa",
  capital:" ハラレ / Harare",
  population:" 約1670万人 / ~16.7M",
  populationRank:72,
  landarea:" ~391K km²",
  areaRank:61,
  currency:" ジンバブエ・ゴールド / ZiG",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"スイス",
  en:"switzerland",
  code:"ch",
  continent:"europe",
  capital:" ベルン / Bern",
  population:" 約890万人 / ~8.9M",
  populationRank:98,
  landarea:" ~41.3K km²",
  areaRank:130,
  currency:" スイスフラン / CHF",
  language:" ドイツ語 / French",
  aliases:[]
},
{
  jp:"スウェーデン",
  en:"sweden",
  code:"se",
  continent:"europe",
  capital:" ストックホルム / Stockholm",
  population:" 約1050万人 / ~10.5M",
  populationRank:88,
  landarea:" ~450K km²",
  areaRank:57,
  currency:" スウェーデン・クローナ / SEK",
  language:" スウェーデン語 / Swedish",
  aliases:[]
},
{
  jp:"スーダン",
  en:"sudan",
  code:"sd",
  continent:"africa",
  capital:" ハルツーム / Khartoum",
  population:" 約5000万人 / ~50M",
  populationRank:30,
  landarea:" ~1,886K km²",
  areaRank:15,
  currency:" スーダン・ポンド / SDG",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"スペイン",
  en:"spain",
  code:"es",
  continent:"europe",
  capital:" マドリード / Madrid",
  population:" 約4800万人 / ~48M",
  populationRank:31,
  landarea:" ~506K km²",
  areaRank:51,
  currency:" ユーロ / EUR",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"スリナム",
  en:"suriname",
  code:"sr",
  continent:"southamerica",
  capital:" パラマリボ / Paramaribo",
  population:" 約63万人 / ~0.63M",
  populationRank:174,
  landarea:" ~164K km²",
  areaRank:92,
  currency:" スリナム・ドル / SRD",
  language:" オランダ語 / Dutch",
  aliases:[]
},
{
  jp:"スリランカ",
  en:"sri lanka",
  code:"lk",
  continent:"asia",
  capital:" スリジャヤワルダナプラコッテ / Sri Jayawardenepura Kotte",
  population:" 約2200万人 / ~22M",
  populationRank:60,
  landarea:" ~65.6K km²",
  areaRank:122,
  currency:" スリランカ・ルピー / LKR",
  language:" シンハラ語 / Tamil",
  aliases:[]
},
{
  jp:"スロバキア",
  en:"slovakia",
  code:"sk",
  continent:"europe",
  capital:" ブラチスラバ / Bratislava",
  population:" 約540万人 / ~5.4M",
  populationRank:120,
  landarea:" ~49K km²",
  areaRank:128,
  currency:" ユーロ / EUR",
  language:" スロバキア語 / Slovak",
  aliases:[]
},
{
  jp:"スロベニア",
  en:"slovenia",
  code:"si",
  continent:"europe",
  capital:" リュブリャナ / Ljubljana",
  population:" 約210万人 / ~2.1M",
  populationRank:147,
  landarea:" ~20.3K km²",
  areaRank:154,
  currency:" ユーロ / EUR",
  language:" スロベニア語 / Slovene",
  aliases:[]
},
{
  jp:"セーシェル",
  en:"seychelles",
  code:"sc",
  continent:"africa",
  capital:" ビクトリア / Victoria",
  population:" 約11万人 / ~0.11M",
  populationRank:192,
  landarea:" ~0.46K km²",
  areaRank:181,
  currency:" セーシェル・ルピー / SCR",
  language:" セーシェル・クレオール語 / English",
  aliases:[]
},
{
  jp:"セネガル",
  en:"senegal",
  code:"sn",
  continent:"africa",
  capital:" ダカール / Dakar",
  population:" 約1850万人 / ~18.5M",
  populationRank:66,
  landarea:" ~197K km²",
  areaRank:86,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"セルビア",
  en:"serbia",
  code:"rs",
  continent:"europe",
  capital:" ベオグラード / Belgrade",
  population:" 約660万人 / ~6.6M",
  populationRank:111,
  landarea:" ~88.4K km²",
  areaRank:111,
  currency:" セルビア・ディナール / RSD",
  language:" セルビア語 / Serbian",
  aliases:[]
},
{
  jp:"セントクリストファーネイビス",
  en:"saint kitts and nevis",
  code:"kn",
  continent:"northamerica",
  capital:" バセテール / Basseterre",
  population:" 約5万人 / ~0.05M",
  populationRank:194,
  landarea:" ~0.26K km²",
  areaRank:185,
  currency:" 東カリブドル / XCD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"セントビンセントおよびグレナディーン諸島",
  en:"saint vincent and the grenadines",
  code:"vc",
  continent:"northamerica",
  capital:" キングスタウン / Kingstown",
  population:" 約10万人 / ~0.10M",
  populationRank:193,
  landarea:" ~0.39K km²",
  areaRank:184,
  currency:" 東カリブドル / XCD",
  language:" 英語 / English",
  aliases:["セントビンセントおよびグレナディーンしょとう","せんとびんせんとおよびぐれなでぃーんしょとう"]
},
{
  jp:"セントルシア",
  en:"saint lucia",
  code:"lc",
  continent:"northamerica",
  capital:" カストリーズ / Castries",
  population:" 約18万人 / ~0.18M",
  populationRank:186,
  landarea:" ~0.62K km²",
  areaRank:177,
  currency:" 東カリブドル / XCD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ソマリア",
  en:"somalia",
  code:"so",
  continent:"africa",
  capital:" モガディシュ / Mogadishu",
  population:" 約1800万人 / ~18M",
  populationRank:68,
  landarea:" ~637K km²",
  areaRank:43,
  currency:" ソマリア・シリング / SOS",
  language:" ソマリ語 / Arabic",
  aliases:[]
},
{
  jp:"ソロモン諸島",
  en:"solomon islands",
  code:"sb",
  continent:"oceania",
  capital:" ホニアラ / Honiara",
  population:" 約75万人 / ~0.75M",
  populationRank:171,
  landarea:" ~28.9K km²",
  areaRank:139,
  currency:" ソロモン諸島ドル / SBD",
  language:" 英語 / English",
  aliases:["そろもんしょとう","ソロモンショトウ"]
},
{
  jp:"タイ",
  en:"thailand",
  code:"th",
  continent:"asia",
  capital:" バンコク / Bangkok",
  population:" 約7100万人 / ~71M",
  populationRank:20,
  landarea:" ~513K km²",
  areaRank:50,
  currency:" バーツ / THB",
  language:" タイ語 / Thai",
  aliases:[]
},
{
  jp:"タジキスタン",
  en:"tajikistan",
  code:"tj",
  continent:"asia",
  capital:" ドゥシャンベ / Dushanbe",
  population:" 約1000万人 / ~10M",
  populationRank:90,
  landarea:" ~143K km²",
  areaRank:94,
  currency:" ソモニ / TJS",
  language:" タジク語 / Tajik",
  aliases:[]
},
{
  jp:"タンザニア",
  en:"tanzania",
  code:"tz",
  continent:"africa",
  capital:" ドドマ / Dodoma",
  population:" 約6700万人 / ~67M",
  populationRank:23,
  landarea:" ~947K km²",
  areaRank:31,
  currency:" タンザニア・シリング / TZS",
  language:" スワヒリ語 / English",
  aliases:[]
},
{
  jp:"チェコ",
  en:"czech republic",
  code:"cz",
  continent:"europe",
  capital:" プラハ / Prague",
  population:" 約1070万人 / ~10.7M",
  populationRank:86,
  landarea:" ~78.9K km²",
  areaRank:116,
  currency:" コルナ / CZK",
  language:" チェコ語 / Czech",
  aliases:[]
},
{
  jp:"チャド",
  en:"chad",
  code:"td",
  continent:"africa",
  capital:" ンジャメナ / N'Djamena",
  population:" 約1800万人 / ~18M",
  populationRank:69,
  landarea:" ~1,284K km²",
  areaRank:20,
  currency:" CFAフラン / XAF",
  language:" フランス語 / Arabic",
  aliases:[]
},
{
  jp:"チュニジア",
  en:"tunisia",
  code:"tn",
  continent:"africa",
  capital:" チュニス / Tunis",
  population:" 約1200万人 / ~12M",
  populationRank:78,
  landarea:" ~164K km²",
  areaRank:93,
  currency:" ディナール / TND",
  language:" アラビア語 / French",
  aliases:[]
},
{
  jp:"チリ",
  en:"chile",
  code:"cl",
  continent:"southamerica",
  capital:" サンティアゴ / Santiago",
  population:" 約2000万人 / ~20M",
  populationRank:62,
  landarea:" ~756K km²",
  areaRank:38,
  currency:" ペソ / CLP",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"ツバル",
  en:"tuvalu",
  code:"tv",
  continent:"oceania",
  capital:" フナフティ / Funafuti",
  population:" 約1万人 / ~0.01M",
  populationRank:197,
  landarea:" ~0.03K km²",
  areaRank:190,
  currency:" 豪ドル / AUD",
  language:" ツバル語 / English",
  aliases:[]
},
{
  jp:"デンマーク",
  en:"denmark",
  code:"dk",
  continent:"europe",
  capital:" コペンハーゲン / Copenhagen",
  population:" 約600万人 / ~6M",
  populationRank:114,
  landarea:" ~43K km²",
  areaRank:132,
  currency:" クローネ / DKK",
  language:" デンマーク語 / Danish",
  aliases:[]
},
{
  jp:"ドイツ",
  en:"germany",
  code:"de",
  continent:"europe",
  capital:" ベルリン / Berlin",
  population:" 約8300万人 / ~83M",
  populationRank:19,
  landarea:" ~357K km²",
  areaRank:63,
  currency:" ユーロ / EUR",
  language:" ドイツ語 / German",
  aliases:[]
},
{
  jp:"トーゴ",
  en:"togo",
  code:"tg",
  continent:"africa",
  capital:" ロメ / Lomé",
  population:" 約900万人 / ~9M",
  populationRank:96,
  landarea:" ~56.8K km²",
  areaRank:125,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"ドミニカ共和国",
  en:"dominican republic",
  code:"do",
  continent:"northamerica",
  capital:" サントドミンゴ / Santo Domingo",
  population:" 約1100万人 / ~11M",
  populationRank:84,
  landarea:" ~48.7K km²",
  areaRank:129,
  currency:" ペソ / DOP",
  language:" スペイン語 / Spanish",
  aliases:["ドミニカキョウワコク","どみにかきょうわこく"]
},
{
  jp:"ドミニカ国",
  en:"dominica",
  code:"dm",
  continent:"northamerica",
  capital:" ロゾー / Roseau",
  population:" 約7万人 / ~0.07M",
  populationRank:196,
  landarea:" ~0.75K km²",
  areaRank:178,
  currency:" 東カリブドル / XCD",
  language:" 英語 / English",
  aliases:["ドミニカコク","どみにかこく"]
},
{
  jp:"トリニダードトバゴ",
  en:"trinidad and tobago",
  code:"tt",
  continent:"northamerica",
  capital:" ポートオブスペイン / Port of Spain",
  population:" 約140万人 / ~1.4M",
  populationRank:152,
  landarea:" ~5.1K km²",
  areaRank:168,
  currency:" TTドル / TTD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"トルクメニスタン",
  en:"turkmenistan",
  code:"tm",
  continent:"asia",
  capital:" アシガバート / Ashgabat",
  population:" 約650万人 / ~6.5M",
  populationRank:113,
  landarea:" ~488K km²",
  areaRank:52,
  currency:" マナト / TMT",
  language:" トルクメン語 / Turkmen",
  aliases:[]
},
{
  jp:"トルコ",
  en:"turkey",
  code:"tr",
  continent:"asia",
  capital:" アンカラ / Ankara",
  population:" 約8500万人 / ~85M",
  populationRank:18,
  landarea:" ~783K km²",
  areaRank:36,
  currency:" リラ / TRY",
  language:" トルコ語 / Turkish",
  aliases:[]
},
{
  jp:"トンガ",
  en:"tonga",
  code:"to",
  continent:"oceania",
  capital:" ヌクアロファ / Nuku'alofa",
  population:" 約10万人 / ~0.1M",
  populationRank:192,
  landarea:" ~0.75K km²",
  areaRank:177,
  currency:" パアンガ / TOP",
  language:" トンガ語 / English",
  aliases:[]
},
{
  jp:"ナイジェリア",
  en:"nigeria",
  code:"ng",
  continent:"africa",
  capital:" アブジャ / Abuja",
  population:" 約2.2億人 / ~220M",
  populationRank:6,
  landarea:" ~924K km²",
  areaRank:32,
  currency:" ナイラ / NGN",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ナウル",
  en:"nauru",
  code:"nr",
  continent:"oceania",
  capital:" ヤレン / Yaren",
  population:" 約1万人 / ~0.01M",
  populationRank:198,
  landarea:" ~0.02K km²",
  areaRank:191,
  currency:" 豪ドル / AUD",
  language:" ナウル語 / English",
  aliases:[]
},
{
  jp:"ナミビア",
  en:"namibia",
  code:"na",
  continent:"africa",
  capital:" ウィントフック / Windhoek",
  population:" 約260万人 / ~2.6M",
  populationRank:140,
  landarea:" ~824K km²",
  areaRank:34,
  currency:" ナミビア・ドル / NAD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ニカラグア",
  en:"nicaragua",
  code:"ni",
  continent:"northamerica",
  capital:" マナグア / Managua",
  population:" 約700万人 / ~7M",
  populationRank:109,
  landarea:" ~130K km²",
  areaRank:98,
  currency:" コルドバ / NIO",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"ニジェール",
  en:"niger",
  code:"ne",
  continent:"africa",
  capital:" ニアメ / Niamey",
  population:" 約2700万人 / ~27M",
  populationRank:54,
  landarea:" ~1,267K km²",
  areaRank:21,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"ニュージーランド",
  en:"new zealand",
  code:"nz",
  continent:"oceania",
  capital:" ウェリントン / Wellington",
  population:" 約520万人 / ~5.2M",
  populationRank:121,
  landarea:" ~268K km²",
  areaRank:73,
  currency:" NZドル / NZD",
  language:" 英語 / Maori",
  aliases:[]
},
{
  jp:"ネパール",
  en:"nepal",
  code:"np",
  continent:"asia",
  capital:" カトマンズ / Kathmandu",
  population:" 約3000万人 / ~30M",
  populationRank:49,
  landarea:" ~147K km²",
  areaRank:93,
  currency:" ルピー / NPR",
  language:" ネパール語 / Nepali",
  aliases:[]
},
{
  jp:"ノルウェー",
  en:"norway",
  code:"no",
  continent:"europe",
  capital:" オスロ / Oslo",
  population:" 約550万人 / ~5.5M",
  populationRank:119,
  landarea:" ~385K km²",
  areaRank:62,
  currency:" クローネ / NOK",
  language:" ノルウェー語 / Norwegian",
  aliases:[]
},
{
  jp:"バーレーン",
  en:"bahrain",
  code:"bh",
  continent:"asia",
  capital:" マナーマ / Manama",
  population:" 約150万人 / ~1.5M",
  populationRank:150,
  landarea:" ~0.77K km²",
  areaRank:176,
  currency:" ディナール / BHD",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"ハイチ",
  en:"haiti",
  code:"ht",
  continent:"northamerica",
  capital:" ポルトープランス / Port-au-Prince",
  population:" 約1150万人 / ~11.5M",
  populationRank:82,
  landarea:" ~27.8K km²",
  areaRank:143,
  currency:" グールド / HTG",
  language:" フランス語 / Haitian Creole",
  aliases:[]
},
{
  jp:"パキスタン",
  en:"pakistan",
  code:"pk",
  continent:"asia",
  capital:" イスラマバード / Islamabad",
  population:" 約2.4億人 / ~240M",
  populationRank:5,
  landarea:" ~881K km²",
  areaRank:33,
  currency:" ルピー / PKR",
  language:" ウルドゥー語 / English",
  aliases:[]
},
{
  jp:"バチカン",
  en:"vatican city",
  code:"va",
  continent:"europe",
  capital:" バチカン / Vatican City",
  population:" 約800人 / ~0.0008M",
  populationRank:199,
  landarea:" ~0.00044K km²",
  areaRank:196,
  currency:" ユーロ / EUR",
  language:" ラテン語 / Italian",
  aliases:["バチカン市国","vatican"]
},
{
  jp:"パナマ",
  en:"panama",
  code:"pa",
  continent:"northamerica",
  capital:" パナマシティ / Panama City",
  population:" 約450万人 / ~4.5M",
  populationRank:127,
  landarea:" ~75K km²",
  areaRank:116,
  currency:" バルボア / USD",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"バヌアツ",
  en:"vanuatu",
  code:"vu",
  continent:"oceania",
  capital:" ポートビラ / Port Vila",
  population:" 約33万人 / ~0.33M",
  populationRank:182,
  landarea:" ~12.2K km²",
  areaRank:157,
  currency:" バツ / VUV",
  language:" ビスラマ語 / English",
  aliases:[]
},
{
  jp:"バハマ",
  en:"bahamas",
  code:"bs",
  continent:"northamerica",
  capital:" ナッソー / Nassau",
  population:" 約40万人 / ~0.4M",
  populationRank:178,
  landarea:" ~13.9K km²",
  areaRank:155,
  currency:" バハマドル / BSD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"パプアニューギニア",
  en:"papua new guinea",
  code:"pg",
  continent:"oceania",
  capital:" ポートモレスビー / Port Moresby",
  population:" 約1000万人 / ~10M",
  populationRank:91,
  landarea:" ~463K km²",
  areaRank:55,
  currency:" キナ / PGK",
  language:" 英語 / Tok Pisin",
  aliases:[]
},
{
  jp:"パラオ",
  en:"palau",
  code:"pw",
  continent:"oceania",
  capital:" マルキョク / Ngerulmud",
  population:" 約2万人 / ~0.02M",
  populationRank:194,
  landarea:" ~0.46K km²",
  areaRank:179,
  currency:" 米ドル / USD",
  language:" パラオ語 / English",
  aliases:[]
},
{
  jp:"パラグアイ",
  en:"paraguay",
  code:"py",
  continent:"southamerica",
  capital:" アスンシオン / Asunción",
  population:" 約700万人 / ~7M",
  populationRank:108,
  landarea:" ~407K km²",
  areaRank:60,
  currency:" グアラニー / PYG",
  language:" スペイン語 / Guarani",
  aliases:[]
},
{
  jp:"バルバドス",
  en:"barbados",
  code:"bb",
  continent:"northamerica",
  capital:" ブリッジタウン / Bridgetown",
  population:" 約28万人 / ~0.28M",
  populationRank:183,
  landarea:" ~0.43K km²",
  areaRank:182,
  currency:" バルバドス・ドル / BBD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ハンガリー",
  en:"hungary",
  code:"hu",
  continent:"europe",
  capital:" ブダペスト / Budapest",
  population:" 約960万人 / ~9.6M",
  populationRank:94,
  landarea:" ~93K km²",
  areaRank:108,
  currency:" フォリント / HUF",
  language:" ハンガリー語 / Hungarian",
  aliases:[]
},
{
  jp:"バングラデシュ",
  en:"bangladesh",
  code:"bd",
  continent:"asia",
  capital:" ダッカ / Dhaka",
  population:" 約1.7億人 / ~170M",
  populationRank:8,
  landarea:" ~148K km²",
  areaRank:92,
  currency:" タカ / BDT",
  language:" ベンガル語 / Bengali",
  aliases:[]
},
{
  jp:"フィジー",
  en:"fiji",
  code:"fj",
  continent:"oceania",
  capital:" スバ / Suva",
  population:" 約90万人 / ~0.9M",
  populationRank:168,
  landarea:" ~18.3K km²",
  areaRank:156,
  currency:" フィジードル / FJD",
  language:" 英語 / Fijian",
  aliases:[]
},
{
  jp:"フィリピン",
  en:"philippines",
  code:"ph",
  continent:"asia",
  capital:" マニラ / Manila",
  population:" 約1.1億人 / ~110M",
  populationRank:13,
  landarea:" ~300K km²",
  areaRank:72,
  currency:" ペソ / PHP",
  language:" フィリピノ語 / English",
  aliases:[]
},
{
  jp:"フィンランド",
  en:"finland",
  code:"fi",
  continent:"europe",
  capital:" ヘルシンキ / Helsinki",
  population:" 約560万人 / ~5.6M",
  populationRank:118,
  landarea:" ~338K km²",
  areaRank:64,
  currency:" ユーロ / EUR",
  language:" フィンランド語 / Swedish",
  aliases:[]
},
{
  jp:"ブータン",
  en:"bhutan",
  code:"bt",
  continent:"asia",
  capital:" ティンプー / Thimphu",
  population:" 約80万人 / ~0.8M",
  populationRank:170,
  landarea:" ~38.4K km²",
  areaRank:134,
  currency:" ニュルタム / BTN",
  language:" ゾンカ語 / Dzongkha",
  aliases:[]
},
{
  jp:"ブラジル",
  en:"brazil",
  code:"br",
  continent:"southamerica",
  capital:" ブラジリア / Brasília",
  population:" 約2.1億人 / ~210M",
  populationRank:7,
  landarea:" ~8,516K km²",
  areaRank:5,
  currency:" レアル / BRL",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"フランス",
  en:"france",
  code:"fr",
  continent:"europe",
  capital:" パリ / Paris",
  population:" 約6500万人 / ~65M",
  populationRank:23,
  landarea:" ~551K km²",
  areaRank:48,
  currency:" ユーロ / EUR",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"ブルガリア",
  en:"bulgaria",
  code:"bg",
  continent:"europe",
  capital:" ソフィア / Sofia",
  population:" 約670万人 / ~6.7M",
  populationRank:111,
  landarea:" ~111K km²",
  areaRank:104,
  currency:" レフ / BGN",
  language:" ブルガリア語 / Bulgarian",
  aliases:[]
},
{
  jp:"ブルキナファソ",
  en:"burkina faso",
  code:"bf",
  continent:"africa",
  capital:" ワガドゥグー / Ouagadougou",
  population:" 約2300万人 / ~23M",
  populationRank:58,
  landarea:" ~274K km²",
  areaRank:74,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"ブルネイ",
  en:"brunei",
  code:"bn",
  continent:"asia",
  capital:" バンダルスリブガワン / Bandar Seri Begawan",
  population:" 約45万人 / ~0.45M",
  populationRank:177,
  landarea:" ~5.8K km²",
  areaRank:169,
  currency:" ブルネイドル / BND",
  language:" マレー語 / Malay",
  aliases:[]
},
{
  jp:"ブルンジ",
  en:"burundi",
  code:"bi",
  continent:"africa",
  capital:" ギテガ / Gitega",
  population:" 約1300万人 / ~13M",
  populationRank:76,
  landarea:" ~27.8K km²",
  areaRank:144,
  currency:" ブルンジ・フラン / BIF",
  language:" ルンディ語 / French",
  aliases:[]
},
{
  jp:"ベトナム",
  en:"vietnam",
  code:"vn",
  continent:"asia",
  capital:" ハノイ / Hanoi",
  population:" 約1億人 / ~100M",
  populationRank:15,
  landarea:" ~331K km²",
  areaRank:66,
  currency:" ドン / VND",
  language:" ベトナム語 / Vietnamese",
  aliases:[]
},
{
  jp:"ベナン",
  en:"benin",
  code:"bj",
  continent:"africa",
  capital:" ポルトノボ / Porto-Novo",
  population:" 約1400万人 / ~14M",
  populationRank:74,
  landarea:" ~114K km²",
  areaRank:102,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"ベネズエラ",
  en:"venezuela",
  code:"ve",
  continent:"southamerica",
  capital:" カラカス / Caracas",
  population:" 約2800万人 / ~28M",
  populationRank:51,
  landarea:" ~916K km²",
  areaRank:33,
  currency:" ボリバル / VES",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"ベラルーシ",
  en:"belarus",
  code:"by",
  continent:"europe",
  capital:" ミンスク / Minsk",
  population:" 約920万人 / ~9.2M",
  populationRank:95,
  landarea:" ~207K km²",
  areaRank:84,
  currency:" ルーブル / BYN",
  language:" ベラルーシ語 / Russian",
  aliases:[]
},
{
  jp:"ベリーズ",
  en:"belize",
  code:"bz",
  continent:"northamerica",
  capital:" ベルモパン / Belmopan",
  population:" 約40万人 / ~0.4M",
  populationRank:179,
  landarea:" ~22.9K km²",
  areaRank:148,
  currency:" ベリーズドル / BZD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ペルー",
  en:"peru",
  code:"pe",
  continent:"southamerica",
  capital:" リマ / Lima",
  population:" 約3400万人 / ~34M",
  populationRank:46,
  landarea:" ~1,285K km²",
  areaRank:19,
  currency:" ソル / PEN",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"ベルギー",
  en:"belgium",
  code:"be",
  continent:"europe",
  capital:" ブリュッセル / Brussels",
  population:" 約1200万人 / ~12M",
  populationRank:80,
  landarea:" ~30.5K km²",
  areaRank:137,
  currency:" ユーロ / EUR",
  language:" フランス語 / Dutch",
  aliases:[]
},
{
  jp:"ポーランド",
  en:"poland",
  code:"pl",
  continent:"europe",
  capital:" ワルシャワ / Warsaw",
  population:" 約3800万人 / ~38M",
  populationRank:40,
  landarea:" ~312K km²",
  areaRank:69,
  currency:" ズウォティ / PLN",
  language:" ポーランド語 / Polish",
  aliases:[]
},
{
  jp:"ボスニアヘルツェゴビナ",
  en:"bosnia and herzegovina",
  code:"ba",
  continent:"europe",
  capital:" サラエボ / Sarajevo",
  population:" 約320万人 / ~3.2M",
  populationRank:136,
  landarea:" ~51K km²",
  areaRank:127,
  currency:" マルク / BAM",
  language:" ボスニア語 / Serbian",
  aliases:[]
},
{
  jp:"ボツワナ",
  en:"botswana",
  code:"bw",
  continent:"africa",
  capital:" ハボローネ / Gaborone",
  population:" 約260万人 / ~2.6M",
  populationRank:141,
  landarea:" ~582K km²",
  areaRank:46,
  currency:" プラ / BWP",
  language:" 英語 / Tswana",
  aliases:[]
},
{
  jp:"ボリビア",
  en:"bolivia",
  code:"bo",
  continent:"southamerica",
  capital:" スクレ / Sucre",
  population:" 約1200万人 / ~12M",
  populationRank:81,
  landarea:" ~1,099K km²",
  areaRank:28,
  currency:" ボリビアーノ / BOB",
  language:" スペイン語 / Quechua",
  aliases:[]
},
{
  jp:"ポルトガル",
  en:"portugal",
  code:"pt",
  continent:"europe",
  capital:" リスボン / Lisbon",
  population:" 約1000万人 / ~10M",
  populationRank:90,
  landarea:" ~92K km²",
  areaRank:110,
  currency:" ユーロ / EUR",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"ホンジュラス",
  en:"honduras",
  code:"hn",
  continent:"northamerica",
  capital:" テグシガルパ / Tegucigalpa",
  population:" 約1000万人 / ~10M",
  populationRank:89,
  landarea:" ~112K km²",
  areaRank:103,
  currency:" レンピラ / HNL",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"マーシャル諸島",
  en:"marshall islands",
  code:"mh",
  continent:"oceania",
  capital:" マジュロ / Majuro",
  population:" 約6万人 / ~0.06M",
  populationRank:195,
  landarea:" ~0.18K km²",
  areaRank:186,
  currency:" 米ドル / USD",
  language:" マーシャル語 / English",
  aliases:["marshall","まーしゃるしょとう","マーシャルショトウ"]
},
{
  jp:"マダガスカル",
  en:"madagascar",
  code:"mg",
  continent:"africa",
  capital:" アンタナナリボ / Antananarivo",
  population:" 約3000万人 / ~30M",
  populationRank:48,
  landarea:" ~587K km²",
  areaRank:45,
  currency:" アリアリ / MGA",
  language:" マダガスカル語 / French",
  aliases:[]
},
{
  jp:"マラウイ",
  en:"malawi",
  code:"mw",
  continent:"africa",
  capital:" リロングウェ / Lilongwe",
  population:" 約2000万人 / ~20M",
  populationRank:61,
  landarea:" ~118K km²",
  areaRank:100,
  currency:" クワチャ / MWK",
  language:" 英語 / Chichewa",
  aliases:[]
},
{
  jp:"マリ",
  en:"mali",
  code:"ml",
  continent:"africa",
  capital:" バマコ / Bamako",
  population:" 約2300万人 / ~23M",
  populationRank:59,
  landarea:" ~1,240K km²",
  areaRank:24,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"マルタ",
  en:"malta",
  code:"mt",
  continent:"europe",
  capital:" バレッタ / Valletta",
  population:" 約50万人 / ~0.5M",
  populationRank:176,
  landarea:" ~0.32K km²",
  areaRank:184,
  currency:" ユーロ / EUR",
  language:" マルタ語 / English",
  aliases:[]
},
{
  jp:"マレーシア",
  en:"malaysia",
  code:"my",
  continent:"asia",
  capital:" クアラルンプール / Kuala Lumpur",
  population:" 約3400万人 / ~34M",
  populationRank:45,
  landarea:" ~330K km²",
  areaRank:67,
  currency:" リンギット / MYR",
  language:" マレー語 / English",
  aliases:[]
},
{
  jp:"ミクロネシア",
  en:"micronesia",
  code:"fm",
  continent:"oceania",
  capital:" パリキール / Palikir",
  population:" 約11万人 / ~0.11M",
  populationRank:192,
  landarea:" ~0.70K km²",
  areaRank:178,
  currency:" 米ドル / USD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ミャンマー",
  en:"myanmar",
  code:"mm",
  continent:"asia",
  capital:" ネピドー / Naypyidaw",
  population:" 約5500万人 / ~55M",
  populationRank:26,
  landarea:" ~676K km²",
  areaRank:40,
  currency:" チャット / MMK",
  language:" ビルマ語 / Burmese",
  aliases:[]
},
{
  jp:"メキシコ",
  en:"mexico",
  code:"mx",
  continent:"northamerica",
  capital:" メキシコシティ / Mexico City",
  population:" 約1.3億人 / ~130M",
  populationRank:10,
  landarea:" ~1,964K km²",
  areaRank:13,
  currency:" ペソ / MXN",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"モーリシャス",
  en:"mauritius",
  code:"mu",
  continent:"africa",
  capital:" ポートルイス / Port Louis",
  population:" 約130万人 / ~1.3M",
  populationRank:155,
  landarea:" ~2.0K km²",
  areaRank:170,
  currency:" ルピー / MUR",
  language:" 英語 / French",
  aliases:[]
},
{
  jp:"モーリタニア",
  en:"mauritania",
  code:"mr",
  continent:"africa",
  capital:" ヌアクショット / Nouakchott",
  population:" 約500万人 / ~5M",
  populationRank:123,
  landarea:" ~1,030K km²",
  areaRank:29,
  currency:" ウギア / MRU",
  language:" アラビア語 / French",
  aliases:[]
},
{
  jp:"モザンビーク",
  en:"mozambique",
  code:"mz",
  continent:"africa",
  capital:" マプト / Maputo",
  population:" 約3300万人 / ~33M",
  populationRank:50,
  landarea:" ~801K km²",
  areaRank:35,
  currency:" メティカル / MZN",
  language:" ポルトガル語 / Portuguese",
  aliases:[]
},
{
  jp:"モナコ",
  en:"monaco",
  code:"mc",
  continent:"europe",
  capital:" モナコ / Monaco",
  population:" 約4万人 / ~0.04M",
  populationRank:196,
  landarea:" ~0.002K km²",
  areaRank:195,
  currency:" ユーロ / EUR",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"モルディブ",
  en:"maldives",
  code:"mv",
  continent:"asia",
  capital:" マレ / Malé",
  population:" 約50万人 / ~0.5M",
  populationRank:175,
  landarea:" ~0.30K km²",
  areaRank:185,
  currency:" ルフィア / MVR",
  language:" ディベヒ語 / English",
  aliases:[]
},
{
  jp:"モルドバ",
  en:"moldova",
  code:"md",
  continent:"europe",
  capital:" キシナウ / Chișinău",
  population:" 約260万人 / ~2.6M",
  populationRank:140,
  landarea:" ~33.8K km²",
  areaRank:135,
  currency:" レウ / MDL",
  language:" ルーマニア語 / Romanian",
  aliases:[]
},
{
  jp:"モロッコ",
  en:"morocco",
  code:"ma",
  continent:"africa",
  capital:" ラバト / Rabat",
  population:" 約3700万人 / ~37M",
  populationRank:42,
  landarea:" ~446K km²",
  areaRank:56,
  currency:" ディルハム / MAD",
  language:" アラビア語 / French",
  aliases:[]
},
{
  jp:"モンテネグロ",
  en:"montenegro",
  code:"me",
  continent:"europe",
  capital:" ポドゴリツァ / Podgorica",
  population:" 約60万人 / ~0.6M",
  populationRank:173,
  landarea:" ~13.8K km²",
  areaRank:155,
  currency:" ユーロ / EUR",
  language:" モンテネグロ語 / Serbian",
  aliases:[]
},
{
  jp:"ヨルダン",
  en:"jordan",
  code:"jo",
  continent:"asia",
  capital:" アンマン / Amman",
  population:" 約1100万人 / ~11M",
  populationRank:83,
  landarea:" ~89K km²",
  areaRank:112,
  currency:" ディナール / JOD",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"ラオス",
  en:"laos",
  code:"la",
  continent:"asia",
  capital:" ビエンチャン / Vientiane",
  population:" 約750万人 / ~7.5M",
  populationRank:105,
  landarea:" ~236K km²",
  areaRank:82,
  currency:" キープ / LAK",
  language:" ラオス語 / Lao",
  aliases:[]
},
{
  jp:"ラトビア",
  en:"latvia",
  code:"lv",
  continent:"europe",
  capital:" リガ / Riga",
  population:" 約190万人 / ~1.9M",
  populationRank:148,
  landarea:" ~64.6K km²",
  areaRank:124,
  currency:" ユーロ / EUR",
  language:" ラトビア語 / Latvian",
  aliases:[]
},
{
  jp:"リトアニア",
  en:"lithuania",
  code:"lt",
  continent:"europe",
  capital:" ビリニュス / Vilnius",
  population:" 約280万人 / ~2.8M",
  populationRank:139,
  landarea:" ~65.3K km²",
  areaRank:123,
  currency:" ユーロ / EUR",
  language:" リトアニア語 / Lithuanian",
  aliases:[]
},
{
  jp:"リビア",
  en:"libya",
  code:"ly",
  continent:"africa",
  capital:" トリポリ / Tripoli",
  population:" 約700万人 / ~7M",
  populationRank:108,
  landarea:" ~1,760K km²",
  areaRank:16,
  currency:" ディナール / LYD",
  language:" アラビア語 / Arabic",
  aliases:[]
},
{
  jp:"リヒテンシュタイン",
  en:"liechtenstein",
  code:"li",
  continent:"europe",
  capital:" ファドゥーツ / Vaduz",
  population:" 約4万人 / ~0.04M",
  populationRank:197,
  landarea:" ~0.16K km²",
  areaRank:189,
  currency:" スイスフラン / CHF",
  language:" ドイツ語 / German",
  aliases:[]
},
{
  jp:"リベリア",
  en:"liberia",
  code:"lr",
  continent:"africa",
  capital:" モンロビア / Monrovia",
  population:" 約550万人 / ~5.5M",
  populationRank:120,
  landarea:" ~111K km²",
  areaRank:103,
  currency:" リベリア・ドル / LRD",
  language:" 英語 / English",
  aliases:[]
},
{
  jp:"ルーマニア",
  en:"romania",
  code:"ro",
  continent:"europe",
  capital:" ブカレスト / Bucharest",
  population:" 約1900万人 / ~19M",
  populationRank:64,
  landarea:" ~238K km²",
  areaRank:81,
  currency:" レウ / RON",
  language:" ルーマニア語 / Romanian",
  aliases:[]
},
{
  jp:"ルクセンブルク",
  en:"luxembourg",
  code:"lu",
  continent:"europe",
  capital:" ルクセンブルク / Luxembourg",
  population:" 約65万人 / ~0.65M",
  populationRank:174,
  landarea:" ~2.6K km²",
  areaRank:167,
  currency:" ユーロ / EUR",
  language:" ルクセンブルク語 / French",
  aliases:[]
},
{
  jp:"ルワンダ",
  en:"rwanda",
  code:"rw",
  continent:"africa",
  capital:" キガリ / Kigali",
  population:" 約1400万人 / ~14M",
  populationRank:73,
  landarea:" ~26.3K km²",
  areaRank:145,
  currency:" ルワンダ・フラン / RWF",
  language:" ルワンダ語 / French",
  aliases:[]
},
{
  jp:"レソト",
  en:"lesotho",
  code:"ls",
  continent:"africa",
  capital:" マセル / Maseru",
  population:" 約230万人 / ~2.3M",
  populationRank:144,
  landarea:" ~30.4K km²",
  areaRank:137,
  currency:" ロチ / LSL",
  language:" 英語 / Sesotho",
  aliases:[]
},
{
  jp:"レバノン",
  en:"lebanon",
  code:"lb",
  continent:"asia",
  capital:" ベイルート / Beirut",
  population:" 約550万人 / ~5.5M",
  populationRank:119,
  landarea:" ~10.5K km²",
  areaRank:161,
  currency:" レバノン・ポンド / LBP",
  language:" アラビア語 / French",
  aliases:[]
},
{
  jp:"ロシア",
  en:"russia",
  code:"ru",
  continent:"europe",
  capital:" モスクワ / Moscow",
  population:" 約1.4億人 / ~140M",
  populationRank:9,
  landarea:" ~17,098K km²",
  areaRank:1,
  currency:" ルーブル / RUB",
  language:" ロシア語 / Russian",
  aliases:[]
},
{
  jp:"韓国",
  en:"korea",
  code:"kr",
  continent:"asia",
  capital:" ソウル / Seoul",
  population:" 約5100万人 / ~51M",
  populationRank:28,
  landarea:" ~100K km²",
  areaRank:110,
  currency:" ウォン / KRW",
  language:" 韓国語 / Korean",
  aliases:["大韓民国","かんこく","だいかんみんこく"]
},
{
  jp:"赤道ギニア",
  en:"equatorial guinea",
  code:"gq",
  continent:"africa",
  capital:" マラボ / Malabo",
  population:" 約180万人 / ~1.8M",
  populationRank:149,
  landarea:" ~28K km²",
  areaRank:141,
  currency:" CFAフラン / XAF",
  language:" スペイン語 / French",
  aliases:["せきどうぎにあ","セキドウギニア"]
},
{
  jp:"中央アフリカ",
  en:"central african republic",
  code:"cf",
  continent:"africa",
  capital:" バンギ / Bangui",
  population:" 約550万人 / ~5.5M",
  populationRank:118,
  landarea:" ~623K km²",
  areaRank:44,
  currency:" CFAフラン / XAF",
  language:" フランス語 / Sango",
  aliases:["centralafrican","ちゅうおうあふりか","チュウオウアフリカ"]
},
{
  jp:"中国",
  en:"china",
  code:"cn",
  continent:"asia",
  capital:" 北京 / Beijing",
  population:" 約14.1億人 / ~1410M",
  populationRank:2,
  landarea:" ~9,597K km²",
  areaRank:4,
  currency:" 元 / CNY",
  language:" 中国語 / Mandarin",
  aliases:["中華人民共和国","ちゅうごく","ちゅうかじんみんきょうわこく"]
},
{
  jp:"東ティモール",
  en:"east timor",
  code:"tl",
  continent:"asia",
  capital:" ディリ / Dili",
  population:" 約140万人 / ~1.4M",
  populationRank:151,
  landarea:" ~14.9K km²",
  areaRank:156,
  currency:" 米ドル / USD",
  language:" テトゥン語 / Portuguese",
  aliases:["Timor Leste","ひがしてぃもーる","ヒガシティモール"]
},
{
  jp:"南アフリカ",
  en:"south africa",
  code:"za",
  continent:"africa",
  capital:" プレトリア / Pretoria",
  population:" 約6200万人 / ~62M",
  populationRank:24,
  landarea:" ~1,221K km²",
  areaRank:25,
  currency:" ランド / ZAR",
  language:" 英語 / Zulu",
  aliases:["みなみあふりか","ミナミアフリカ"]
},
{
  jp:"南スーダン",
  en:"south sudan",
  code:"ss",
  continent:"africa",
  capital:" ジュバ / Juba",
  population:" 約1100万人 / ~11M",
  populationRank:83,
  landarea:" ~644K km²",
  areaRank:42,
  currency:" 南スーダン・ポンド / SSP",
  language:" 英語 / English",
  aliases:["みなみすーだん","ミナミスーダン"]
},
{
  jp:"日本",
  en:"japan",
  code:"jp",
  continent:"asia",
  capital:" 東京 / Tokyo",
  population:" 約1.2億人 / ~120M",
  populationRank:11,
  landarea:" ~378K km²",
  areaRank:61,
  currency:" 円 / JPY(¥)",
  language:" 日本語 / Japanese",
  aliases:["にほん","にっぽん","ニホン","ニッポン"]
},
{
  jp:"北マケドニア",
  en:"north macedonia",
  code:"mk",
  continent:"europe",
  capital:" スコピエ / Skopje",
  population:" 約210万人 / ~2.1M",
  populationRank:147,
  landarea:" ~25.7K km²",
  areaRank:148,
  currency:" デナル / MKD",
  language:" マケドニア語 / Albanian",
  aliases:["きたまけどにあ","キタマケドニア"]
},
{
  jp:"北朝鮮",
  en:"north korea",
  code:"kp",
  continent:"asia",
  capital:" 平壌 / Pyongyang",
  population:" 約2600万人 / ~26M",
  populationRank:55,
  landarea:" ~120K km²",
  areaRank:99,
  currency:" ウォン / KPW",
  language:" 朝鮮語 / Korean",
  aliases:["朝鮮民主主義人民共和国","ちょうせんみんしゅしゅぎじんみんきょうわこく","きたちょうせん"]
},
{
  jp:"キューバ",
  en:"cuba",
  code:"cu",
  continent:"northamerica",
  capital:" ハバナ / Havana",
  population:" 約1100万人 / ~11M",
  populationRank:85,
  landarea:" ~110K km²",
  areaRank:104,
  currency:" ペソ / CUP",
  language:" スペイン語 / Spanish",
  aliases:[]
},
{
  jp:"イラク",
  en:"iraq",
  code:"iq",
  continent:"asia",
  capital:" バグダッド / Baghdad",
  population:" 約4500万人 / ~45M",
  populationRank:33,
  landarea:" ~438K km²",
  areaRank:58,
  currency:" ディナール / IQD",
  language:" アラビア語 / Kurdish",
  aliases:[]
},
{
  jp:"モンゴル",
  en:"mongolia",
  code:"mn",
  continent:"asia",
  capital:" ウランバートル / Ulaanbaatar",
  population:" 約340万人 / ~3.4M",
  populationRank:134,
  landarea:" ~1,564K km²",
  areaRank:18,
  currency:" トゥグルグ / MNT",
  language:" モンゴル語 / Mongolian",
  aliases:[]
},
{
  jp:"台湾",
  en:"taiwan",
  code:"tw",
  continent:"asia",
  capital:" 台北 / Taipei",
  population:" 約2400万人 / ~24M",
  populationRank:56,
  landarea:" ~36K km²",
  areaRank:136,
  currency:" 台湾ドル / TWD",
  language:" 中国語 / Mandarin",
  aliases:["たいわん","タイワン"]
},
{
  jp:"コソボ",
  en:"kosovo",
  code:"xk",
  continent:"europe",
  capital:" プリシュティナ / Pristina",
  population:" 約180万人 / ~1.8M",
  populationRank:149,
  landarea:" ~10.9K km²",
  areaRank:161,
  currency:" ユーロ / EUR",
  language:" アルバニア語 / Serbian",
  aliases:[]
},
{
  jp:"ニウエ",
  en:"niue",
  code:"nu",
  continent:"oceania",
  capital:" アロフィ / Alofi",
  population:" 約2000人 / ~0.002M",
  populationRank:200,
  landarea:" ~0.26K km²",
  areaRank:186,
  currency:" NZドル / NZD",
  language:" ニウエ語 / English",
  aliases:[]
},
{
  jp:"コートジボワール",
  en:"cote d'ivoire",
  code:"ci",
  continent:"africa",
  capital:" ヤムスクロ / Yamoussoukro",
  population:" 約2800万人 / ~28M",
  populationRank:52,
  landarea:" ~322K km²",
  areaRank:68,
  currency:" CFAフラン / XOF",
  language:" フランス語 / French",
  aliases:[]
},
{
  jp:"クック諸島",
  en:"cook islands",
  code:"ck",
  continent:"oceania",
  capital:" アバルア / Avarua",
  population:" 約2万人 / ~0.02M",
  populationRank:194,
  landarea:" ~0.24K km²",
  areaRank:187,
  currency:" NZドル / NZD",
  language:" 英語 / Maori",
  aliases:["くっくしょとう","クックショトウ","cook"]
},

];